[project]
name = "imputer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.54.4",
    "pandas>=2.2.3",
]

authors = [
    {name = "Shaun Porwal", email = "shaun.porwal@gmail.com"}
]

[dependency-groups]
dev = [
    "jupyterlab>=4.3.0",
    "ruff>=0.7.3",
]
